version: '1.0.0'
services:
  bot:
    container_name: 'Ballsdex-AutoCatcher'
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py"
    volumes:
      - .:/app
      
      