name: Update balls

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # Every 30 minutes

permissions:
  contents: write

  
jobs:
  update:
    name: Update the balls
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.DiscordToken }}
      author: Github Actions
      commit: Updated the balls

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git push/rebase

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Fetching images
      run: node scrapper.js

    - name: Committing changes
      run: |
        git config --global user.name "${{ env.author }}"
        git config --global user.email "username@users.noreply.github.com"
        git add balls
        git commit -m "${{ env.commit }}"
        git pull --rebase --autostash origin main
        git push